### ISSUE TITLE
Remove non-core templates from published package

### ISSUE THREAD

**Issue by wongchito** [railmapgen/rmg-templates#105]
Core templates: Basic, MTR, Guangzhou Metro and Shanghai Metro
Non-core templates: all other companies

Why?
1. The style of non-core companies are not supported in RMG so the templates are not 100% correct. 
2. The number of companies keeps growing after we introduce the automatic template requests. We want to reduce the times of packaging and RMG rebuild, as well as to avoid lengthy company selection on RMG. 

How?
- [x] Split `company-config.json` into 2 files #119 
- [x] Remove non-core templates from package #119 
- [x] Add resources check script #119
- [x] Create a template selection view and used as an app-clip in RMG

Impact?
1. RMG offline (electron) users are not able to import non-core templates
